// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvux0I1I-tN0v731uUQMyAsZzm98LVkTo',
    appId: '1:23399074740:web:623a7bc7c88e16c0af80e1',
    messagingSenderId: '23399074740',
    projectId: 'siakad-app-7dc06',
    authDomain: 'siakad-app-7dc06.firebaseapp.com',
    storageBucket: 'siakad-app-7dc06.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwQ2KwbfiRv0kIFQWSUOKNQBWyw1QHl2Q',
    appId: '1:23399074740:android:fbb843512c7da97caf80e1',
    messagingSenderId: '23399074740',
    projectId: 'siakad-app-7dc06',
    storageBucket: 'siakad-app-7dc06.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCI31Ks_8EXICncFVD2OtoesS88LW52Vc',
    appId: '1:23399074740:ios:935eef13e6de8385af80e1',
    messagingSenderId: '23399074740',
    projectId: 'siakad-app-7dc06',
    storageBucket: 'siakad-app-7dc06.firebasestorage.app',
    iosBundleId: 'com.example.siakadApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCCI31Ks_8EXICncFVD2OtoesS88LW52Vc',
    appId: '1:23399074740:ios:935eef13e6de8385af80e1',
    messagingSenderId: '23399074740',
    projectId: 'siakad-app-7dc06',
    storageBucket: 'siakad-app-7dc06.firebasestorage.app',
    iosBundleId: 'com.example.siakadApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDvux0I1I-tN0v731uUQMyAsZzm98LVkTo',
    appId: '1:23399074740:web:fa10276d3403f82faf80e1',
    messagingSenderId: '23399074740',
    projectId: 'siakad-app-7dc06',
    authDomain: 'siakad-app-7dc06.firebaseapp.com',
    storageBucket: 'siakad-app-7dc06.firebasestorage.app',
  );
}
